name: Deploy to the live server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploying:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 31.97.58.144
          username: root
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            cd /root/aibenmart-node
            pwd
            sudo git pull
            sudo npm install
            sudo pm2 restart qataloog
